### ISSUE TITLE
'blocked user' when trying to login

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [dyseo/AsyncLine#10]
```
  File "/Users/xxxx/Documents/gits/AsyncLine/examples/echo.py", line 5, in <module>
    cl.login(name='test', qr=True)
  File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/main.py", line 113, in login
    self.__validate(name, token, mail, passwd, cert, qr)
  File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/main.py", line 59, in __validate
    f = SyncAsync(self.auth.createLoginSession(name, token, mail, passwd, cert, qr)).run()
  File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/models.py", line 10, in run
    return self.loop(self._coroutine)
  File "/Users/xxxx/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/auth.py", line 95, in createLoginSession
    await self.loginWithQrcode(path=name+".session" if name else None)
  File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/auth.py", line 129, in loginWithQrcode
    lr = await self.call('loginZ', rq)
  File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/lib/Gen/f_LineService.py", line 26096, in loginZ
    return await self._methods['loginZ']([ctx, loginRequest])
  File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/lib/Gen/f_LineService.py", line 26123, in _loginZ
    raise result.e
AsyncLine.lib.Gen.ttypes.TalkException: TalkException(code=35, reason='blocked user', parameterMap=None)
```

This happens however I tried to login (via QR or email/password) I can confirm it is correct because I received login verifications

It says I was logged in on an iPad the first time when I tried to login

**Comment by dyseo** [comment]
> ```
>   File "/Users/xxxx/Documents/gits/AsyncLine/examples/echo.py", line 5, in <module>
>     cl.login(name='test', qr=True)
>   File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/main.py", line 113, in login
>     self.__validate(name, token, mail, passwd, cert, qr)
>   File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/main.py", line 59, in __validate
>     f = SyncAsync(self.auth.createLoginSession(name, token, mail, passwd, cert, qr)).run()
>   File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/models.py", line 10, in run
>     return self.loop(self._coroutine)
>   File "/Users/xxxx/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
>     return future.result()
>   File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/auth.py", line 95, in createLoginSession
>     await self.loginWithQrcode(path=name+".session" if name else None)
>   File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/auth.py", line 129, in loginWithQrcode
>     lr = await self.call('loginZ', rq)
>   File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/lib/Gen/f_LineService.py", line 26096, in loginZ
>     return await self._methods['loginZ']([ctx, loginRequest])
>   File "/Users/xxxx/Documents/gits/AsyncLine/AsyncLine/lib/Gen/f_LineService.py", line 26123, in _loginZ
>     raise result.e
> AsyncLine.lib.Gen.ttypes.TalkException: TalkException(code=35, reason='blocked user', parameterMap=None)
> ```
> 
> This happens however I tried to login (via QR or email/password) I can confirm it is correct because I received login verifications
> 
> It says I was logged in on an iPad the first time when I tried to login

first i say, line will block you if you're using incorrect/not match User-Agent and Line-Application as header
and other reasson if you spam connection to line server
