### ISSUE TITLE
AttributeError: 'Message' object has no attribute '_from'

### ISSUE THREAD

**Issue by fakhrads** [dyseo/AsyncLine#2]
I found this, I dont know if its a bug or not.

Traceback (most recent call last):
  File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\poll.py", line 84, in streams
    await self.execute(k, op.message)
  File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\poll.py", line 61, in execute
    await coro(*args)
  File "tracer.py", line 36, in send_message
    name = (await cl.getContacts(msg._from)).displayName
AttributeError: 'Message' object has no attribute '_from'

**Comment by umeneriman** [comment]
_from →　from_
The name of the object has been changed.
I dont know if its a bug or not.

**Comment by umeneriman** [comment]
"_from" →　"from_"
The name of the object has been changed.
I dont know if its a bug or not.

**Comment by umeneriman** [comment]
The name of the object has been changed.
I dont know if its a bug or not.

> "_from" →　"from_"

**Comment by umeneriman** [comment]
The name of the object has been changed.
I dont know if its a bug or not.

"msg.＿from" →　"msg.from＿"

**Comment by dyseo** [comment]
> The name of the object has been changed.
> I dont know if its a bug or not.
> 
> "msg.＿from" →　"msg.from＿"

it's not bug, i use default service it as `Message.from_` you can see on [ttypes](https://github.com/dyseo/AsyncLine/blob/master/LineSync/lib/Gen/ttypes.py)
