### ISSUE TITLE
kickoutFromGroup invalid contactsId

### ISSUE THREAD

**Issue by fakhrads** [dyseo/AsyncLine#4]
I found this when using operation type 19

```
Traceback (most recent call last):
  File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\poll.py", line 87, in streams
    await self.execute(k, op)
  File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\poll.py", line 62, in execute
    await coro(*args)
  File "bot.py", line 33, in notifed_kick
    await cl.talk.kickoutFromGroup(op.param1,op.param2)
  File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\talk.py", line 547, in kickoutFromGroup
    return bool(await self.auth.call("kickoutFromGroup", 0, group_id, [mid]))
  File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\lib\Gen\f_LineService.py", line 11374, in kickoutFromGroup
    return await self._methods['kickoutFromGroup']([ctx, reqSeq, groupId, contactIds])
  File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\lib\Gen\f_LineService.py", line 11403, in _kickoutFromGroup
    raise result.e
LineSync.lib.Gen.ttypes.TalkException: TalkException(code=0, reason='invalid contactIds', parameterMap={})
```

is this a bug or not I don't know, but here my code
![1564469966481](https://user-images.githubusercontent.com/24514627/62107678-56c2e400-b2d2-11e9-8741-adda03c78ff3.jpg)

**Comment by dyseo** [comment]
> I found this when using operation type 19
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\poll.py", line 87, in streams
>     await self.execute(k, op)
>   File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\poll.py", line 62, in execute
>     await coro(*args)
>   File "bot.py", line 33, in notifed_kick
>     await cl.talk.kickoutFromGroup(op.param1,op.param2)
>   File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\talk.py", line 547, in kickoutFromGroup
>     return bool(await self.auth.call("kickoutFromGroup", 0, group_id, [mid]))
>   File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\lib\Gen\f_LineService.py", line 11374, in kickoutFromGroup
>     return await self._methods['kickoutFromGroup']([ctx, reqSeq, groupId, contactIds])
>   File "C:\Users\Fakhr\Programs\python\asyncline\LineSync\lib\Gen\f_LineService.py", line 11403, in _kickoutFromGroup
>     raise result.e
> LineSync.lib.Gen.ttypes.TalkException: TalkException(code=0, reason='invalid contactIds', parameterMap={})
> ```
> 
> is this a bug or not I don't know, but here my code
> ![1564469966481](https://user-images.githubusercontent.com/24514627/62107678-56c2e400-b2d2-11e9-8741-adda03c78ff3.jpg)

for now you need instance of list from user mid as `cl.talk.kickoutFromGroup(op.param1, [op.param2])`

**Comment by fakhrads** [comment]
> for now you need instance of list from user mid as `cl.talk.kickoutFromGroup(op.param1, [op.param2])`

Thanks for your reply, I didn't realize it before.

**Comment by dyseo** [comment]
> > for now you need instance of list from user mid as `cl.talk.kickoutFromGroup(op.param1, [op.param2])`
> 
> Thanks for your reply, I didn't realize it before.

thanks for reporting, now u can pass a string for user mid or many mid of list
