### ISSUE TITLE
Potential dependency conflicts between asyncline and requests

### ISSUE THREAD

**Issue by NeolithEra** [dyseo/AsyncLine#9]
Hi, as shown in the following full dependency graph of  **_asyncline_**, **_asyncline_** requires **_requests *_** ， while the installed version of **_frugal_**(3.4.1) requires _**requests <3,>=2.12.5**_.

According to Pip's _“first found wins”_ installation strategy, _**requests  2.22.0**_ is the actually installed version.  

Although the first found package version _**requests  2.22.0**_ just satisfies the later dependency constraint （_**requests <3,>=2.12.5**_), it will lead to a build failure once developers release a newer version of requests.

### Dependency tree--------
```
asyncline - 1.5.9.5
| +- aiohttp(install version:3.6.2 version range:*)
| +- aiostomp(install version:1.6.2 version range:*)
| | +- async-timeout(install version:4.0.0a2 version range:*)
| | | +- typing-extensions(install version:3.7.4 version range:>=3.6.5)
| | +- bumpversion(install version:0.5.3 version range:*)
| | +- six(install version:1.13.0 version range:*)
| +- async-timeout(install version:4.0.0a2 version range:*)
| | +- typing-extensions(install version:3.7.4 version range:>=3.6.5)
| +- asyncio-nats-client(install version:0.10.0 version range:*)
| +- frugal(install version:3.4.1 version range:*)
| | +- requests(install version:2.22.0 version range:<3,>=2.12.5)
| | | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| | +- six(install version:1.13.0 version range:>=1.10.0,<2)
| | +- thrift(install version:0.10.0 version range:==0.10.0)
| | | +- six(install version:1.13.0 version range:>=1.7.2)
| +- requests(install version:2.22.0 version range:*)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- rsa(install version:4.0 version range:*)
| | +- pyasn1(install version:0.4.8 version range:>=0.1.3)
| +- ujson(install version:1.35 version range:*)
| +- pymongo(install version:3.10.0 version range:*) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependencies to be **_requests <3_**.
2.	Ask your upstream project **_frugal_** to lose the version range of **_requests_** to be **_>=2.12.5_**.

@dyseo Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by dyseo** [comment]
> ### Suggested Solution
> 1. Fix your direct dependencies to be **_requests <3_**.
> 2. Ask your upstream project **_frugal_** to lose the version range of **_requests_** to be **_>=2.12.5_**.
> 
> @dyseo Which solution do you prefer, 1 or 2?
> Please let me know your choice. May I pull a request to solve this issue?

Thanks for the notice, I'm very busy to take care of this so I'm very happy if you want to help out some issues on asyncline, for the simplest possible first choice i think @NeolithEra
